099

diff --git a/.github/workflows/immortalwrt-all.yml b/.github/workflows/immortalwrt-all.yml
--- a/.github/workflows/immortalwrt-all.yml
+++ b/.github/workflows/immortalwrt-all.yml
@@ -263,13 +263,21 @@ jobs:
       run: |
         git config --global user.name "GitHub Actions"
         git config --global user.email "actions@github.com"
-        # 检查 config/immortalwrt.info 文件是否有更改
+        # 检查 config/immortalwrt.info 文件是否有更改，如果有更改则提交更新
         if ! git diff --quiet -- config/immortalwrt.info; then
-        git add config/immortalwrt.info
-        git commit -m "Update .config file"
-        git push origin ${{ github.ref }}
-        else
-        echo "No changes in .config file to commit."
+          git add config/immortalwrt.info
+          git commit -m "Update .config file"
+          git pull origin ${{ github.ref }}
+          for i in {1..3}; do
+            git push origin ${{ github.ref }} && break || echo "Retrying git push ($i/3)..."
+            sleep 5
+          done
+          if [ $? -ne 0 ]; then
+            echo "Failed to push changes after 3 attempts."
+            exit 1
+          fi
+          echo "[INFO] No changes in .config file to commit."
+          echo "No changes in .config file to commit."
         fi
 
     # - name: 检查空间使用情况
